export const events = [
  {
    title: "Web Summit 2026",
    image: "/images/event1.png",
    slug: "web-summit-2026",
    location: "Lisbon, Portugal",
    date: "November 9-12, 2026",
    time: "9:00 AM WET",
  },
  {
    title: "AWS re:Invent 2026",
    image: "/images/event2.png",
    slug: "aws-reinvent-2026",
    location: "Las Vegas, Nevada",
    date: "November 30-December 4, 2026",
    time: "9:00 AM PST",
  },
  {
    title: "GitHub Universe",
    image: "/images/event3.png",
    slug: "github-universe",
    location: "San Francisco, California",
    date: "October 2026",
    time: "9:00 AM PDT",
  },
  {
    title: "KubeCon + CloudNativeCon North America",
    image: "/images/event4.png",
    slug: "kubecon-cloudnativecon-north-america",
    location: "Salt Lake City, Utah",
    date: "November 2026",
    time: "9:00 AM MDT",
  },
  {
    title: "PyCon US",
    image: "/images/event5.png",
    slug: "pycon-us",
    location: "United States",
    date: "May 2027",
    time: "9:00 AM local time",
  },
  {
    title: "FOSDEM 2027",
    image: "/images/event6.png",
    slug: "fosdem-2027",
    location: "Brussels, Belgium",
    date: "February 2027",
    time: "9:00 AM CET",
  },
];
